### ISSUE TITLE
install 

### ISSUE THREAD

**Issue by cathalgking** [waldronlab/VisiumIO#1]
I am trying to install VisiumIO but am having an issue. I am running R version:

```{r}
R version 4.3.2 (2023-10-31)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Sonoma 14.3
```
I try to install with:
```{r}
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

# The following initializes usage of Bioc devel
BiocManager::install(version='devel')

BiocManager::install("VisiumIO")
```
And I get the Error
```{r}
Error: Bioconductor version '3.19' requires R version '4.4'; use `version = '3.18'` with R version 4.3; see
  https://bioconductor.org/install
```
I already have R 4.3.2 and there does not seem to be a version 4.4 that exists

**Comment by lwaldron** [comment]
Hi @cathalgking ,
R 4.4 is referring to the unreleased devel version of R - see https://contributions.bioconductor.org/use-devel.html for some more information on using the devel version of Bioconductor and links for installing R-devel. Since VisiumIO is pre-release it hasn't been tested against the current release version of Bioconductor, but after this April's release of Bioconductor 3.19 it will become installable with a regular Bioconductor release installation. To be honest I don't know if the package would work with a current bioc-release (@LiNk-NY might have a better idea), although it's possible to try by downloading your own version of the package, changing the DESCRIPTION file, and building/installing locally (definitely voids the non-existent warranty :) ).

**Comment by LiNk-NY** [comment]
Hi @cathalgking 

Thank you for your interest. `VisiumIO` currently doesn't work with Bioconductor 3.18 because
I made updates to `TENxIO` in devel. Those changes are not bug fixes but feature updates and thus were not ported to the stable release. You'd have to wait until the next Bioconductor release or use Bioc-devel as Levi mentioned. 

Best regards,
Marcel

**Comment by cathalgking** [comment]
Ok, thanks for your work on this and the prompt replies @LiNk-NY @lwaldron 
Ill await the full release of ```VisiumIO```.
I mainly wanted to be able to read in a 10x Visium dataset to an SPE object with SpatialExperiment but getting an error and dont know why.
`Error in names(xyz) <- names(sfs) <- sids : 
  'names' attribute [1] must be the same length as the vector [0]`

**Comment by LiNk-NY** [comment]
@cathalgking Perhaps it's a bug in `SpatialExperiment`. Feel free to report it with a reproducible example to our collaborator Dario Righelli at https://github.com/drighelli/SpatialExperiment/issues 
Thanks!
